jobs:
  test:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: stable
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            toolchain: stable
            target: x86_64-apple-darwin
          - os: macos-latest
            toolchain: stable
            target: aarch64-apple-darwin
          - os: windows-latest
            toolchain: stable
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            toolchain: stable
            target: x86_64-pc-windows-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}

      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
