name: WebAssembly builds

on: push

jobs:
  build:
    name: ${{ matrix.target }} ${{ matrix.interface }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: wasm32-wasip1
            interface: plain
            features: ""
          - target: wasm32-wasip1
            interface: WAI
            features: --features wasmer-wai
          - target: wasm32-wasip2
            interface: plain
            features: ""
          - target: wasm32-wasip2
            interface: component
            features: --features wasi-component
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build and link
        run: cargo test --release --target ${{ matrix.target }} ${{ matrix.features }} --no-run
